version: '3.1'
services:
  app:
    container_name: api-container
    image: tiklaisgelsin:0.0.1
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookstore